/**
 * Centralized mock data store for fallback when DATABASE_URL is not configured.
 * This allows the ops hub to work in demo mode without a real database.
 */

export const DEFAULT_TENANT_ID = "santos";

export const mockPatients = [
  {
    id: "1",
    tenantId: DEFAULT_TENANT_ID,
    referenceNumber: "HIMT-2026-0042",
    name: "James Mwangi",
    country: "Kenya",
    phone: "+254 712 345 678",
    email: "james.mwangi@email.com",
    whatsapp: "+254 712 345 678",
    treatmentType: "Orthopedic (Hip/Knee Replacement)",
    treatmentDescription: "Bilateral hip replacement",
    preferredHospital: "Aster Medcity",
    stage: "CONFIRMATION",
    assignedCoordinatorId: "2",
    estimatedCost: 12500,
    depositReceived: true,
    depositAmount: 3000,
    finalCost: null,
    inquiryDate: "2026-06-20T00:00:00.000Z",
    expectedTravelDate: "2026-07-15T00:00:00.000Z",
    actualTravelDate: null,
    dischargeDate: null,
  },
  {
    id: "2",
    tenantId: DEFAULT_TENANT_ID,
    referenceNumber: "HIMT-2026-0041",
    name: "Fatima Al-Hassan",
    country: "UAE",
    phone: "+971 50 123 4567",
    email: "fatima.h@email.com",
    whatsapp: "+971 50 123 4567",
    treatmentType: "Cardiac (Heart Bypass/Valve)",
    treatmentDescription: "Triple bypass surgery",
    preferredHospital: "Amrita Hospital",
    stage: "VISA_TRAVEL",
    assignedCoordinatorId: "3",
    estimatedCost: 18000,
    depositReceived: true,
    depositAmount: 5000,
    finalCost: null,
    inquiryDate: "2026-06-18T00:00:00.000Z",
    expectedTravelDate: "2026-07-10T00:00:00.000Z",
    actualTravelDate: null,
    dischargeDate: null,
  },
  {
    id: "3",
    tenantId: DEFAULT_TENANT_ID,
    referenceNumber: "HIMT-2026-0040",
    name: "Sarah Thompson",
    country: "United Kingdom",
    phone: "+44 7700 900123",
    email: "sarah.t@email.com",
    whatsapp: "+44 7700 900123",
    treatmentType: "Dental",
    treatmentDescription: "Full mouth restoration with All-on-4 implants",
    preferredHospital: null,
    stage: "AYURVEDA_RECOVERY",
    assignedCoordinatorId: "2",
    estimatedCost: 8500,
    depositReceived: true,
    depositAmount: 2000,
    finalCost: 8200,
    inquiryDate: "2026-04-15T00:00:00.000Z",
    expectedTravelDate: "2026-05-01T00:00:00.000Z",
    actualTravelDate: "2026-05-02T00:00:00.000Z",
    dischargeDate: "2026-05-20T00:00:00.000Z",
  },
];

export const mockLeads = [
  {
    id: "1",
    tenantId: DEFAULT_TENANT_ID,
    source: "WHATSAPP",
    campaign: null,
    name: "David Kimani",
    country: "Kenya",
    email: "david.k@email.com",
    phone: "+254 700 111 222",
    status: "QUALIFIED",
    treatmentInterest: "Hip Replacement",
    budgetRange: "$10,000-$15,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    createdAt: "2026-06-25T00:00:00.000Z",
  },
  {
    id: "2",
    tenantId: DEFAULT_TENANT_ID,
    source: "WEBSITE",
    campaign: null,
    name: "Sarah Oduya",
    country: "Nigeria",
    email: "sarah.o@email.com",
    phone: "+234 800 222 333",
    status: "NEW",
    treatmentInterest: "Cardiac Bypass",
    budgetRange: "$15,000-$20,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "cardiac-africa",
    createdAt: "2026-06-27T00:00:00.000Z",
  },
  {
    id: "3",
    tenantId: DEFAULT_TENANT_ID,
    source: "GOOGLE_ADS",
    campaign: "ortho-uk-2026",
    name: "Michael Brown",
    country: "United Kingdom",
    email: "m.brown@email.com",
    phone: "+44 7700 900123",
    status: "CONTACTED",
    treatmentInterest: "Knee Replacement",
    budgetRange: "$12,000-$18,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "ortho-uk-2026",
    createdAt: "2026-06-20T00:00:00.000Z",
  },
  {
    id: "4",
    tenantId: DEFAULT_TENANT_ID,
    source: "FACEBOOK",
    campaign: null,
    name: "Blessing Adeyemi",
    country: "Ghana",
    email: "b.adeyemi@email.com",
    phone: "+233 200 333 444",
    status: "QUALIFIED",
    treatmentInterest: "MS Treatment",
    budgetRange: "$15,000-$25,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: "facebook",
    utmMedium: "social",
    utmCampaign: null,
    createdAt: "2026-06-15T00:00:00.000Z",
  },
  {
    id: "5",
    tenantId: DEFAULT_TENANT_ID,
    source: "REFERRAL",
    campaign: null,
    name: "Emma Watson",
    country: "Germany",
    email: "emma.w@email.com",
    phone: "+49 160 444 555",
    status: "CONVERTED",
    treatmentInterest: "Spine Surgery",
    budgetRange: "$20,000-$30,000",
    convertedToPatientId: "3",
    conversionDate: "2026-04-10T00:00:00.000Z",
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    createdAt: "2026-05-10T00:00:00.000Z",
  },
  {
    id: "6",
    tenantId: DEFAULT_TENANT_ID,
    source: "WHATSAPP",
    campaign: null,
    name: "James Ochieng",
    country: "Kenya",
    email: "james.o@email.com",
    phone: "+254 711 444 555",
    status: "NEW",
    treatmentInterest: "Ayurveda",
    budgetRange: "$5,000-$8,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    createdAt: "2026-06-28T00:00:00.000Z",
  },
];

export const mockPartners = [
  {
    id: "1",
    tenantId: DEFAULT_TENANT_ID,
    name: "Aster Medcity",
    category: "HOSPITAL",
    contactPerson: "Dr. Prem Nair",
    phone: "+91 484 400 8000",
    email: "prem.nair@asterhospital.com",
    address: "Kochi, Kerala",
    agreementStatus: "SIGNED",
    agreementDate: "2025-12-01T00:00:00.000Z",
    commissionRate: 5,
    totalPatientsReferred: 12,
    totalRevenue: 180000,
    responseTime: 4,
    satisfactionScore: 4.7,
  },
  {
    id: "2",
    tenantId: DEFAULT_TENANT_ID,
    name: "Amrita Hospital",
    category: "HOSPITAL",
    contactPerson: "Dr. Sanjay Chand",
    phone: "+91 487 242 8000",
    email: "sanjay@amrita.edu",
    address: "Kochi, Kerala",
    agreementStatus: "SIGNED",
    agreementDate: "2025-12-15T00:00:00.000Z",
    commissionRate: 4,
    totalPatientsReferred: 8,
    totalRevenue: 120000,
    responseTime: 6,
    satisfactionScore: 4.5,
  },
  {
    id: "3",
    tenantId: DEFAULT_TENANT_ID,
    name: "Ayush Prana",
    category: "AYURVEDA",
    contactPerson: "Dr. Manu Nair",
    phone: "+91 484 274 1234",
    email: "info@ayushprana.com",
    address: "Kumarakom, Kerala",
    agreementStatus: "SIGNED",
    agreementDate: "2026-01-10T00:00:00.000Z",
    commissionRate: 10,
    totalPatientsReferred: 15,
    totalRevenue: 45000,
    responseTime: 3,
    satisfactionScore: 4.9,
  },
  {
    id: "4",
    tenantId: DEFAULT_TENANT_ID,
    name: "Sunrise Hospital",
    category: "HOSPITAL",
    contactPerson: "Dr. Anil Pillai",
    phone: "+91 484 414 0000",
    email: "info@sunrisehospital.com",
    address: "Kochi, Kerala",
    agreementStatus: "PENDING",
    agreementDate: null,
    commissionRate: 5,
    totalPatientsReferred: 0,
    totalRevenue: 0,
    responseTime: null,
    satisfactionScore: null,
  },
];

export const mockTasks = [
  {
    id: "1",
    tenantId: DEFAULT_TENANT_ID,
    title: "Follow up with James Mwangi on visa status",
    description: "Confirm travel dates and visa status",
    type: "PATIENT",
    patientId: "1",
    assignedToId: "2",
    createdById: "1",
    status: "PENDING",
    priority: "HIGH",
    dueDate: "2026-07-02T00:00:00.000Z",
    completedAt: null,
    recurring: null,
  },
  {
    id: "2",
    tenantId: DEFAULT_TENANT_ID,
    title: "Send treatment plan to Fatima Al-Hassan",
    description: "Include cost breakdown and hospital options",
    type: "PATIENT",
    patientId: "2",
    assignedToId: "3",
    createdById: "1",
    status: "PENDING",
    priority: "MEDIUM",
    dueDate: "2026-07-03T00:00:00.000Z",
    completedAt: null,
    recurring: null,
  },
  {
    id: "3",
    tenantId: DEFAULT_TENANT_ID,
    title: "Schedule Ayurveda session for Sarah Thompson",
    description: "Week 4 recovery program at Ayush Prana",
    type: "PATIENT",
    patientId: "3",
    assignedToId: "2",
    createdById: "1",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    dueDate: "2026-07-01T00:00:00.000Z",
    completedAt: null,
    recurring: null,
  },
];

export const mockDocuments = [
  {
    id: "1",
    tenantId: DEFAULT_TENANT_ID,
    title: "HEAL_INDIA_OPERATIONS_MANUAL.md",
    category: "Operations Manual",
    filePath: "/docs/HEAL_INDIA_OPERATIONS_MANUAL.md",
    fileType: "md",
    size: 92000,
    patientId: null,
    partnerId: null,
    uploadedById: "1",
    isPublic: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "2",
    tenantId: DEFAULT_TENANT_ID,
    title: "EMAIL_TEMPLATES_HOSPITAL_OUTREACH.md",
    category: "Email Templates",
    filePath: "/docs/EMAIL_TEMPLATES_HOSPITAL_OUTREACH.md",
    fileType: "md",
    size: 21000,
    patientId: null,
    partnerId: null,
    uploadedById: "1",
    isPublic: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "3",
    tenantId: DEFAULT_TENANT_ID,
    title: "WHATSAPP_MESSAGE_TEMPLATES.md",
    category: "WhatsApp Scripts",
    filePath: "/docs/WHATSAPP_MESSAGE_TEMPLATES.md",
    fileType: "md",
    size: 42000,
    patientId: null,
    partnerId: null,
    uploadedById: "1",
    isPublic: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "4",
    tenantId: DEFAULT_TENANT_ID,
    title: "Ayush Prana Partnership Agreement",
    category: "Partnership",
    filePath: "/docs/ayush-prana-agreement.pdf",
    fileType: "pdf",
    size: 245000,
    patientId: null,
    partnerId: "3",
    uploadedById: "1",
    isPublic: false,
    createdAt: "2026-06-15T00:00:00.000Z",
  },
];

export const mockUsers = [
  {
    id: "1",
    tenantId: DEFAULT_TENANT_ID,
    email: "admin@santos.care",
    name: "Admin",
    phone: null,
    role: "ADMIN",
    avatar: null,
    passwordHash: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "2",
    tenantId: DEFAULT_TENANT_ID,
    email: "priya@santos.care",
    name: "Priya Sharma",
    phone: "+91 999 111 2222",
    role: "COORDINATOR",
    avatar: null,
    passwordHash: null,
    isActive: true,
    createdAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "3",
    tenantId: DEFAULT_TENANT_ID,
    email: "rahul@santos.care",
    name: "Rahul Kumar",
    phone: "+91 999 333 4444",
    role: "COORDINATOR",
    avatar: null,
    passwordHash: null,
    isActive: true,
    createdAt: "2026-02-01T00:00:00.000Z",
  },
];

export const mockBlogPosts = [
  {
    id: "1",
    tenantId: DEFAULT_TENANT_ID,
    title: "MS Treatment in India: Complete Cost Guide 2026",
    slug: "ms-treatment-india-cost-guide",
    excerpt: "Compare MS treatment costs in India vs USA, UK, Kenya. Save up to 80% at JCI hospitals. Full cost breakdown, top hospitals, and recovery included.",
    content: "# MS Treatment in India\n\nComplete guide...",
    imageUrl: "https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=1200",
    category: "Cost Guide",
    tags: ["MS", "multiple sclerosis", "cost guide"],
    status: "PUBLISHED",
    author: "Priya Sharma",
    publishDate: "2026-06-15T00:00:00.000Z",
    createdAt: "2026-06-10T00:00:00.000Z",
    updatedAt: "2026-06-15T00:00:00.000Z",
  },
  {
    id: "2",
    tenantId: DEFAULT_TENANT_ID,
    title: "How to Plan Your Medical Trip to India from Kenya",
    slug: "medical-trip-india-from-kenya-guide",
    excerpt: "Complete guide for Kenyan patients traveling to India for medical treatment. Includes visa process, flight booking, hospital selection, and cost-saving tips.",
    content: "# Medical Trip to India from Kenya\n\nComplete guide...",
    imageUrl: "https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=1200",
    category: "Country Guide",
    tags: ["Kenya", "medical tourism", "travel guide"],
    status: "PUBLISHED",
    author: "Rahul Kumar",
    publishDate: "2026-06-18T00:00:00.000Z",
    createdAt: "2026-06-12T00:00:00.000Z",
    updatedAt: "2026-06-18T00:00:00.000Z",
  },
  {
    id: "3",
    tenantId: DEFAULT_TENANT_ID,
    title: "Why Thousands of Europeans Are Choosing India for Surgery",
    slug: "why-europeans-choose-india-surgery",
    excerpt: "Discover why European patients choose India for surgery: 80% cost savings, JCI-accredited hospitals, zero waiting lists, and Ayurveda recovery.",
    content: "# Why Europeans Choose India\n\nDetailed analysis...",
    imageUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200",
    category: "Market Insight",
    tags: ["Europe", "medical tourism", "cost comparison"],
    status: "PUBLISHED",
    author: "Priya Sharma",
    publishDate: "2026-06-22T00:00:00.000Z",
    createdAt: "2026-06-15T00:00:00.000Z",
    updatedAt: "2026-06-22T00:00:00.000Z",
  },
  {
    id: "4",
    tenantId: DEFAULT_TENANT_ID,
    title: "Brain Tumor Surgery in India: Top Hospitals, Doctors & Costs",
    slug: "brain-tumor-surgery-india-cost-hospitals",
    excerpt: "Brain tumor surgery in India costs $5,000-$12,000 vs $50,000-$150,000 in USA. Top neurosurgeons, JCI hospitals, success rates, and recovery guide.",
    content: "# Brain Tumor Surgery in India\n\nComprehensive guide...",
    imageUrl: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=1200",
    category: "Cost Guide",
    tags: ["brain tumor", "neurosurgery", "cost guide"],
    status: "PUBLISHED",
    author: "Priya Sharma",
    publishDate: "2026-06-28T00:00:00.000Z",
    createdAt: "2026-06-20T00:00:00.000Z",
    updatedAt: "2026-06-28T00:00:00.000Z",
  },
  {
    id: "5",
    tenantId: DEFAULT_TENANT_ID,
    title: "Medical Tourism from Tanzania to India: Complete Guide",
    slug: "medical-tourism-tanzania-india-guide",
    excerpt: "Complete guide for Tanzanian patients seeking treatment in India. Costs, visa process, flight routes, hospital partners, and patient stories.",
    content: "# Medical Tourism Tanzania to India\n\nFull guide...",
    imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=1200",
    category: "Country Guide",
    tags: ["Tanzania", "medical tourism", "travel guide"],
    status: "PUBLISHED",
    author: "Rahul Kumar",
    publishDate: "2026-07-02T00:00:00.000Z",
    createdAt: "2026-06-25T00:00:00.000Z",
    updatedAt: "2026-07-02T00:00:00.000Z",
  },
  {
    id: "6",
    tenantId: DEFAULT_TENANT_ID,
    title: "Patient Story: Margaret's Heart Surgery Journey from Kenya",
    slug: "patient-story-margaret-heart-surgery-kenya",
    excerpt: "Margaret from Kenya shares her heart bypass surgery journey in India. How she saved $30,000, found the right hospital, and recovered fully.",
    content: "# Margaret's Heart Surgery Journey\n\nPatient story...",
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200",
    category: "Patient Story",
    tags: ["patient story", "heart surgery", "Kenya"],
    status: "PUBLISHED",
    author: "Priya Sharma",
    publishDate: "2026-07-05T00:00:00.000Z",
    createdAt: "2026-06-28T00:00:00.000Z",
    updatedAt: "2026-07-05T00:00:00.000Z",
  },
];
