/**
 * Centralized mock data store for fallback when DATABASE_URL is not configured.
 * This allows the ops hub to work in demo mode without a real database.
 */

export const mockPatients = [
  {
    id: "1",
    referenceNumber: "HIMT-2026-0042",
    name: "James Mwangi",
    country: "Kenya",
    phone: "+254 712 345 678",
    email: "james.mwangi@email.com",
    whatsapp: "+254 712 345 678",
    treatmentType: "Orthopedic (Hip/Knee Replacement)",
    treatmentDescription: "Bilateral hip replacement",
    preferredHospital: "Aster Medcity",
    stage: "CONFIRMATION",
    assignedCoordinatorId: "2",
    estimatedCost: 12500,
    depositReceived: true,
    depositAmount: 3000,
    finalCost: null,
    inquiryDate: "2026-06-20T00:00:00.000Z",
    expectedTravelDate: "2026-07-15T00:00:00.000Z",
    actualTravelDate: null,
    dischargeDate: null,
  },
  {
    id: "2",
    referenceNumber: "HIMT-2026-0041",
    name: "Fatima Al-Hassan",
    country: "UAE",
    phone: "+971 50 123 4567",
    email: "fatima.h@email.com",
    whatsapp: "+971 50 123 4567",
    treatmentType: "Cardiac (Heart Bypass/Valve)",
    treatmentDescription: "Triple bypass surgery",
    preferredHospital: "Amrita Hospital",
    stage: "VISA_TRAVEL",
    assignedCoordinatorId: "3",
    estimatedCost: 18000,
    depositReceived: true,
    depositAmount: 5000,
    finalCost: null,
    inquiryDate: "2026-06-18T00:00:00.000Z",
    expectedTravelDate: "2026-07-10T00:00:00.000Z",
    actualTravelDate: null,
    dischargeDate: null,
  },
  {
    id: "3",
    referenceNumber: "HIMT-2026-0040",
    name: "Sarah Thompson",
    country: "United Kingdom",
    phone: "+44 7700 900123",
    email: "sarah.t@email.com",
    whatsapp: "+44 7700 900123",
    treatmentType: "Dental",
    treatmentDescription: "Full mouth restoration with All-on-4 implants",
    preferredHospital: null,
    stage: "AYURVEDA_RECOVERY",
    assignedCoordinatorId: "2",
    estimatedCost: 8500,
    depositReceived: true,
    depositAmount: 2000,
    finalCost: 8200,
    inquiryDate: "2026-04-15T00:00:00.000Z",
    expectedTravelDate: "2026-05-01T00:00:00.000Z",
    actualTravelDate: "2026-05-02T00:00:00.000Z",
    dischargeDate: "2026-05-20T00:00:00.000Z",
  },
];

export const mockLeads = [
  {
    id: "1",
    source: "WHATSAPP",
    campaign: null,
    name: "David Kimani",
    country: "Kenya",
    email: "david.k@email.com",
    phone: "+254 700 111 222",
    status: "QUALIFIED",
    treatmentInterest: "Hip Replacement",
    budgetRange: "$10,000-$15,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    createdAt: "2026-06-25T00:00:00.000Z",
  },
  {
    id: "2",
    source: "WEBSITE",
    campaign: null,
    name: "Sarah Oduya",
    country: "Nigeria",
    email: "sarah.o@email.com",
    phone: "+234 800 222 333",
    status: "NEW",
    treatmentInterest: "Cardiac Bypass",
    budgetRange: "$15,000-$20,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "cardiac-africa",
    createdAt: "2026-06-27T00:00:00.000Z",
  },
  {
    id: "3",
    source: "GOOGLE_ADS",
    campaign: "ortho-uk-2026",
    name: "Michael Brown",
    country: "United Kingdom",
    email: "m.brown@email.com",
    phone: "+44 7700 900123",
    status: "CONTACTED",
    treatmentInterest: "Knee Replacement",
    budgetRange: "$12,000-$18,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "ortho-uk-2026",
    createdAt: "2026-06-20T00:00:00.000Z",
  },
  {
    id: "4",
    source: "FACEBOOK",
    campaign: null,
    name: "Blessing Adeyemi",
    country: "Ghana",
    email: "b.adeyemi@email.com",
    phone: "+233 200 333 444",
    status: "QUALIFIED",
    treatmentInterest: "MS Treatment",
    budgetRange: "$15,000-$25,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: "facebook",
    utmMedium: "social",
    utmCampaign: null,
    createdAt: "2026-06-15T00:00:00.000Z",
  },
  {
    id: "5",
    source: "REFERRAL",
    campaign: null,
    name: "Emma Watson",
    country: "Germany",
    email: "emma.w@email.com",
    phone: "+49 160 444 555",
    status: "CONVERTED",
    treatmentInterest: "Spine Surgery",
    budgetRange: "$20,000-$30,000",
    convertedToPatientId: "3",
    conversionDate: "2026-04-10T00:00:00.000Z",
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    createdAt: "2026-05-10T00:00:00.000Z",
  },
  {
    id: "6",
    source: "WHATSAPP",
    campaign: null,
    name: "James Ochieng",
    country: "Kenya",
    email: "james.o@email.com",
    phone: "+254 711 444 555",
    status: "NEW",
    treatmentInterest: "Ayurveda",
    budgetRange: "$5,000-$8,000",
    convertedToPatientId: null,
    conversionDate: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    createdAt: "2026-06-28T00:00:00.000Z",
  },
];

export const mockPartners = [
  {
    id: "1",
    name: "Aster Medcity",
    category: "HOSPITAL",
    contactPerson: "Dr. Prem Nair",
    phone: "+91 484 400 8000",
    email: "prem.nair@asterhospital.com",
    address: "Kochi, Kerala",
    agreementStatus: "SIGNED",
    agreementDate: "2025-12-01T00:00:00.000Z",
    commissionRate: 5,
    totalPatientsReferred: 12,
    totalRevenue: 180000,
    responseTime: 4,
    satisfactionScore: 4.7,
  },
  {
    id: "2",
    name: "Amrita Hospital",
    category: "HOSPITAL",
    contactPerson: "Dr. Sanjay Chand",
    phone: "+91 487 242 8000",
    email: "sanjay@amrita.edu",
    address: "Kochi, Kerala",
    agreementStatus: "SIGNED",
    agreementDate: "2025-12-15T00:00:00.000Z",
    commissionRate: 4,
    totalPatientsReferred: 8,
    totalRevenue: 120000,
    responseTime: 6,
    satisfactionScore: 4.5,
  },
  {
    id: "3",
    name: "Ayush Prana",
    category: "AYURVEDA",
    contactPerson: "Dr. Manu Nair",
    phone: "+91 484 274 1234",
    email: "info@ayushprana.com",
    address: "Kumarakom, Kerala",
    agreementStatus: "SIGNED",
    agreementDate: "2026-01-10T00:00:00.000Z",
    commissionRate: 10,
    totalPatientsReferred: 15,
    totalRevenue: 45000,
    responseTime: 3,
    satisfactionScore: 4.9,
  },
  {
    id: "4",
    name: "Sunrise Hospital",
    category: "HOSPITAL",
    contactPerson: "Dr. Anil Pillai",
    phone: "+91 484 414 0000",
    email: "info@sunrisehospital.com",
    address: "Kochi, Kerala",
    agreementStatus: "PENDING",
    agreementDate: null,
    commissionRate: 5,
    totalPatientsReferred: 0,
    totalRevenue: 0,
    responseTime: null,
    satisfactionScore: null,
  },
];

export const mockTasks = [
  {
    id: "1",
    title: "Follow up with James Mwangi on visa status",
    description: "Confirm travel dates and visa status",
    type: "PATIENT",
    patientId: "1",
    assignedToId: "2",
    createdById: "1",
    status: "PENDING",
    priority: "HIGH",
    dueDate: "2026-07-02T00:00:00.000Z",
    completedAt: null,
    recurring: null,
  },
  {
    id: "2",
    title: "Send treatment plan to Fatima Al-Hassan",
    description: "Include cost breakdown and hospital options",
    type: "PATIENT",
    patientId: "2",
    assignedToId: "3",
    createdById: "1",
    status: "PENDING",
    priority: "MEDIUM",
    dueDate: "2026-07-03T00:00:00.000Z",
    completedAt: null,
    recurring: null,
  },
  {
    id: "3",
    title: "Schedule Ayurveda session for Sarah Thompson",
    description: "Week 4 recovery program at Ayush Prana",
    type: "PATIENT",
    patientId: "3",
    assignedToId: "2",
    createdById: "1",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    dueDate: "2026-07-01T00:00:00.000Z",
    completedAt: null,
    recurring: null,
  },
];

export const mockDocuments = [
  {
    id: "1",
    title: "HEAL_INDIA_OPERATIONS_MANUAL.md",
    category: "Operations Manual",
    filePath: "/docs/HEAL_INDIA_OPERATIONS_MANUAL.md",
    fileType: "md",
    size: 92000,
    patientId: null,
    partnerId: null,
    uploadedById: "1",
    isPublic: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "2",
    title: "EMAIL_TEMPLATES_HOSPITAL_OUTREACH.md",
    category: "Email Templates",
    filePath: "/docs/EMAIL_TEMPLATES_HOSPITAL_OUTREACH.md",
    fileType: "md",
    size: 21000,
    patientId: null,
    partnerId: null,
    uploadedById: "1",
    isPublic: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "3",
    title: "WHATSAPP_MESSAGE_TEMPLATES.md",
    category: "WhatsApp Scripts",
    filePath: "/docs/WHATSAPP_MESSAGE_TEMPLATES.md",
    fileType: "md",
    size: 42000,
    patientId: null,
    partnerId: null,
    uploadedById: "1",
    isPublic: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "4",
    title: "Ayush Prana Partnership Agreement",
    category: "Partnership",
    filePath: "/docs/ayush-prana-agreement.pdf",
    fileType: "pdf",
    size: 245000,
    patientId: null,
    partnerId: "3",
    uploadedById: "1",
    isPublic: false,
    createdAt: "2026-06-15T00:00:00.000Z",
  },
];

export const mockUsers = [
  {
    id: "1",
    email: "admin@santos.care",
    name: "Admin",
    phone: null,
    role: "ADMIN",
    avatar: null,
    passwordHash: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "2",
    email: "priya@santos.care",
    name: "Priya Sharma",
    phone: "+91 999 111 2222",
    role: "COORDINATOR",
    avatar: null,
    passwordHash: null,
    isActive: true,
    createdAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "3",
    email: "rahul@santos.care",
    name: "Rahul Kumar",
    phone: "+91 999 333 4444",
    role: "COORDINATOR",
    avatar: null,
    passwordHash: null,
    isActive: true,
    createdAt: "2026-02-01T00:00:00.000Z",
  },
];
